name: scan_grumes
description: Application mobile de scan
publish_to: 'none'
version: 1.0.0+12

environment:
  sdk: '>=3.7.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  qr_code_scanner: ^1.0.1
  path_provider: ^2.1.2
  csv: ^5.1.1
  shared_preferences: ^2.2.2
  share_plus: ^7.2.2
  intl: ^0.19.0
  http: ^0.13.6
  google_fonts: ^4.0.4
  ftpconnect: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
    - assets/icon.png
